-- MySQL Script generated by MySQL Workbench
-- 02/04/15 11:48:06
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema jailsys
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema jailsys
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `jailsys` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `jailsys` ;

-- -----------------------------------------------------
-- Table `jailsys`.`ambiente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jailsys`.`ambiente` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `descricao` BLOB NULL,
  `lotacaoPessoas` INT(11) NOT NULL,
  `horarioInicio` TIME NULL,
  `horarioFim` TIME NULL,
  `severidade` VARCHAR(45) NOT NULL,
  `ativo` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jailsys`.`atividade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jailsys`.`atividade` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `ambiente` INT(11) NOT NULL,
  `horarioInicial` TIME NOT NULL,
  `horarioFinal` TIME NOT NULL,
  `ativo` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jailsys`.`pessoa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jailsys`.`pessoa` (
  `id` INT(11) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `CPF` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NULL,
  `dataNasc` DATETIME NOT NULL,
  `celular` VARCHAR(15) NULL,
  `ativo` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jailsys`.`pessoaAtividade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jailsys`.`pessoaAtividade` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `codigoAtividade` INT(11) NOT NULL,
  `codigoPessoa` INT(11) NOT NULL,
  PRIMARY KEY (`id`, `codigoAtividade`, `codigoPessoa`),
  INDEX `FK_ATIVIDADE_idx` (`codigoPessoa` ASC),
  CONSTRAINT `FK_PESSOA_ATIVIDADE`
    FOREIGN KEY (`codigoPessoa`)
    REFERENCES `jailsys`.`pessoa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_ATIVIDADE_ATIVIDADE`
    FOREIGN KEY (`codigoAtividade`)
    REFERENCES `jailsys`.`atividade` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jailsys`.`preso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jailsys`.`preso` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `codigo` VARCHAR(26) NOT NULL,
  `dataPrisao` DATETIME NOT NULL,
  `dataSaida` DATETIME NULL,
  `codigoPessoa` INT(11) NOT NULL,
  `ativo` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_PESSOA_idx` (`codigoPessoa` ASC),
  CONSTRAINT `FK_PRESO_PESSOA`
    FOREIGN KEY (`codigoPessoa`)
    REFERENCES `jailsys`.`pessoa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jailsys`.`crime`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jailsys`.`crime` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `descricao` BLOB NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jailsys`.`funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jailsys`.`funcionario` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `codigo` VARCHAR(45) NOT NULL,
  `cargaHoraria` TIME NOT NULL,
  `dataEntrada` DATETIME NOT NULL,
  `horarioEntrada` TIME NOT NULL,
  `idPessoa` INT(11) NOT NULL,
  `ativo` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_FUNCIONARIO_ATIVIDADES_idx` (`idPessoa` ASC),
  CONSTRAINT `FK_FUNCIONARIO_ATIVIDADES`
    FOREIGN KEY (`idPessoa`)
    REFERENCES `jailsys`.`pessoa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jailsys`.`visita`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jailsys`.`visita` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `idPreso` INT(11) NOT NULL,
  `idPessoa` INT(11) NOT NULL,
  PRIMARY KEY (`id`, `idPreso`, `idPessoa`),
  INDEX `FK_VISITANTE_idx` (`idPessoa` ASC),
  CONSTRAINT `FK_VISITANTE_PESSOA`
    FOREIGN KEY (`idPessoa`)
    REFERENCES `jailsys`.`pessoa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_VISITANTE_PRESO`
    FOREIGN KEY (`idPreso`)
    REFERENCES `jailsys`.`preso` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jailsys`.`crimes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jailsys`.`crimes` (
  `id` INT(11) NOT NULL,
  `idPreso` INT(11) NOT NULL,
  `idCrime` INT(11) NOT NULL,
  PRIMARY KEY (`id`, `idPreso`, `idCrime`),
  INDEX `FK_PRESO_CRIME_idx` (`idPreso` ASC),
  INDEX `FK_CRIME_PRESO_idx` (`idCrime` ASC),
  CONSTRAINT `FK_PRESO_CRIME`
    FOREIGN KEY (`idPreso`)
    REFERENCES `jailsys`.`preso` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_CRIME_CRIME`
    FOREIGN KEY (`idCrime`)
    REFERENCES `jailsys`.`crime` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jailsys`.`atividadeAmbiente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jailsys`.`atividadeAmbiente` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `idAmbiente` INT(11) NOT NULL,
  `idAtividade` INT(11) NOT NULL,
  PRIMARY KEY (`id`, `idAmbiente`, `idAtividade`),
  INDEX `FK_AMBIENTE_ATIVIDADE_idx` (`idAmbiente` ASC),
  INDEX `FK_ATIVIDADE_AMBIENTE_idx` (`idAtividade` ASC),
  CONSTRAINT `FK_AMBIENTE_AMBIENTE`
    FOREIGN KEY (`idAmbiente`)
    REFERENCES `jailsys`.`ambiente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_ATIVIDADE_AMBIENTE`
    FOREIGN KEY (`idAtividade`)
    REFERENCES `jailsys`.`atividade` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jailsys`.`grupo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jailsys`.`grupo` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `descricao` BLOB NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jailsys`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jailsys`.`usuario` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `pessoa` INT(11) NULL,
  `grupo` INT(11) NOT NULL,
  `ativo` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_GRUPO_USUARIO_idx` (`grupo` ASC),
  INDEX `FK_PESSOA_USUARIO_idx` (`pessoa` ASC),
  CONSTRAINT `FK_GRUPO_USUARIO`
    FOREIGN KEY (`grupo`)
    REFERENCES `jailsys`.`grupo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_PESSOA_USUARIO`
    FOREIGN KEY (`pessoa`)
    REFERENCES `jailsys`.`pessoa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
